# Generated by Django 5.2 on 2025-12-30 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apppolizas', '0002_alter_usuario_rol_siniestro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poliza',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='siniestro',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_factura', models.CharField(max_length=50, unique=True)),
                ('documento_contable', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_emision', models.DateField()),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('prima', models.FloatField(help_text='Valor de la prima sobre la cual se calculan impuestos')),
                ('retenciones', models.FloatField(default=0.0)),
                ('contribucion_super', models.FloatField(default=0.0)),
                ('seguro_campesino', models.FloatField(default=0.0)),
                ('derechos_emision', models.FloatField(default=0.0)),
                ('base_imponible', models.FloatField(default=0.0)),
                ('iva', models.FloatField(default=0.0)),
                ('descuento_pronto_pago', models.FloatField(default=0.0)),
                ('total_facturado', models.FloatField(default=0.0)),
                ('valor_a_pagar', models.FloatField(default=0.0)),
                ('mensaje_resultado', models.CharField(blank=True, max_length=255, null=True)),
                ('pagado', models.BooleanField(default=False)),
                ('poliza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas', to='apppolizas.poliza')),
            ],
        ),
    ]
