# Generated by Django 6.0 on 2026-01-01 17:59

import apppolizas.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apppolizas', '0003_alter_poliza_id_alter_siniestro_id_alter_usuario_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='poliza',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='siniestro',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='DocumentoSiniestro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to=apppolizas.models.ruta_documento_siniestro)),
                ('tipo', models.CharField(choices=[('INFORME', 'Informe del Siniestro'), ('FOTOS', 'Fotografías del Siniestro'), ('CEDULA', 'Documentos Personales'), ('FACTURA', 'Facturas de Gastos'), ('OTRO', 'Otros Documentos')], max_length=20)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('siniestro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='apppolizas.siniestro')),
                ('subido_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
